---
- hosts: multi 
  become: yes
  tasks: 


    - name: ensure NTP is installed
      yum: name=ntp state=present
    - name: yum update
      become: true
      yum:
        update_cache: yes
    - name: install NTP if it does not exist 
      shell: | 
        if ! rpm -qa | grep -qw ntp; then 
          yum install -y ntp
        fi
    - name: Ensure ntp is running
      service: name=ntpd state=started enabled=yes
