---
- name: Install apache
  hosts: all 
  become: yes
  tasks: 
    - name: Install apache
      command: yum install --quiet -y httpd httpd-devel 
    - name: install Apache using yum module, better way 
      yum: 
        name: 
          - httpd
          - httpd-devel 
        state: present
    - name: copy config files, best way 
      copy: 
        src: "{{ item.src }}"
        dest: "{{item.dest}}"
        owner: root
        group: root
        mode: 0644
      with_items: 
        - src: httpd.conf
          dest: /etc/httpd/conf/httpd.conf
        - src: httpd-vhosts.conf
          dest: /etc/httpd/conf/httpd-vhosts.conf
    - name: make sure apache is started
        service: 
          name: httpd
          state: started
          enabled: true