---
- name: Install Apache
  hosts: ubuntu

  become: true
  #these variable apply for the play or task in a play 
  environment:
    http_proxy: http://example-proxy:80
    https_proxy: https://example-proxy:80

  vars:
    proxy_vars: 
      http_proxy: http://example-proxy:80
      https_proxy: https://example-proxy:80
    key: value

#  vars_files:
#    - vars/apache_vars.yml
#    - vars/apache_default.yml 
#    - vars/apache-{{ ansible_os_family }}.yml

  handlers: 
    - name: restart apache
      service: 
        name: "{{ apache_service }}"
        state: restarted

  pre_tasks:
    - name: Load variable files
      include_vars: "{{ item }}"
      with_first_found: 
        - "vars/apache_{{ ansible_os_family }}.yml"
        - "vars/apache_default.yml"
  tasks: 
    - debug: var=ansible_os_family

    - debug: msg="{{apache_package}}"

    - name: Ensure Apache is installed.
      package: 
        name: "{{ apache_package }}" 
     
        state: present
      register: foo 
    - debug: var=foo
    - name: copy test  config files. 
      copy: 
        src: ./test.conf
        dest: /etc/httpd/conf.d/test.conf
      notify: restart apache

    # make sure handlers are exected  once after change after the step rather than the end of the playbook
    - name: Make sure handlers are flushed immediately 
      meta: flush_handlers

    - name: Ensure apache is running and starts at boot.
      service: 
        name: httpd
        state: started
        enabled: true

    # whenever we have a notify and a fail, the fail prevents the handler from running at the end of the playbook
    # we can force the handler execution by isong --force-handlers to make sure you want the handler to be ran at the end of your playbook 
    # unless you use the "meta: flush_handlers" 
    # - fail: 

