Vagrant.configure("2") do |config|


  config.ssh.insert_key = false
  #disable shared folder, not needed 
  config.vm.synced_folder  ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v| 
    v.memory = 2048
    v.linked_clone = true
  end
  config.vm.define "apache" do |apache_host|
    apache_host.vm.box= "geerlingguy/centos7"
    apache_host.vm.hostname ="centos"
    apache_host.vm.network :public_network, bridge: "eth0", ip: "172.22.71.45"
    apache_host.vm.network "private_network", ip: "192.168.33.10"

  end

end
