---
- hosts: solr
  become: true 
  vars_files: 
    - vars.yml 
  pre_tasks: 
    - name: Update apt cache if needed.
      apt: 
        update_cache: true 
        cache_valid_time: 3600
  handlers: 
    - name: restart solr
      service: 
        name: solr
        state: restarted
  tasks: 
    - name: Install java 
      apt: 
        name: openjdk-8-jdk 
        state: present

    - name: Download Solr
      get_url: 
        url:  https://dlcdn.apache.org/solr/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz
        #full file name for idempotence
        dest: "{{ download_dir }}/solr-{{solr_version}}.tgz"
        checksum: "{{ solr_checksum }}"
    # we can use unarchive to get and untar, yet Solr requires the tarball, so we need it on the local filesystem
    - name: Expand Solr
      unarchive: 
        src: "{{ download_dir }}/solr-{{solr_version}}.tgz"
        dest: "{{download_dir}}"
        remote_src: true
        # control idempotence, module unarchive might not know if the tarball is unarchived
        creates: "{{download_dir}}/solr-{{solr_version}}/README.txt"
    - name: Run Solr Installations Script
      command: > 
        {{download_dir}}/solr-{{solr_version }}/bin/install_solr_service.sh
        {{download_dir}}/solr-{{solr_version }}.tgz 
        -i /opt
        -d /var/solr
        -u solr
        -s solr
        -p 8983
        creates={{solr_dir}}/bin/solr
    - name: Ensure Solr is started and enabled at boot 
      service: 
        name: solr
        state: started
        enabled: yes 
    